### ISSUE TITLE
label:enhancement Add Elastix, and Ndreg parameters used in the paper

### ISSUE THREAD

**Issue by vzickus** [itsasimiqbal/SeBRe#2]
It would be interesting to know what Elastix and Ndreg (if non default) parameters were used in the paper.

**Comment by itsasimiqbal** [comment]
Hi Vytas,
We used the default parameters of both Elastix and Ndreg for the comparisons in our paper.

**Comment by vzickus** [comment]
Thanks Asim.

For those interested, here are the default parameters for Elastix: http://www.elastix.bigr.nl/wiki/index.php/Default0 

Closing.
