### ISSUE TITLE
Keras package compatibility

### ISSUE THREAD

**Issue by tfppcn** [itsasimiqbal/SeBRe#3]
Hi, I am trying to reproduce the results of your code but ran into some difficulty. May I know which tensorflow and keras packages you used in your code. I tried using keras 2.0.8 which comes with tensorflow 1.10.0 but encountered an error in the Supplementary Figure 4(b) section of the code in SeBRe_feature_processing.ipynb. I got an AssertionError when defining rpn. 

```
~\SeBRe\model.py in run_graph(self, images, outputs)
   2448         outputs = OrderedDict(outputs)
   2449         for o in outputs.values():
-> 2450             assert o is not None
```
I'm very new to coding and python. Any help is appreciated. Thanks.

**Comment by itsasimiqbal** [comment]
Hi, Could you try using the following versions of these packages and see if it works?
TensorFlow 1.3
Keras 2.0.8
