### ISSUE TITLE
Compatibility Issues

### ISSUE THREAD

**Issue by abbystar2** [itsasimiqbal/SeBRe#4]
Hi, I am also trying to reproduce the results of your code and am having multiple compatibility issues. Would you be able to share the version of python you used and the versions of all the packages you used?

**Comment by itsasimiqbal** [comment]
Hi Abby,
I guess we've already communicated through emails. In any case, following are the Python/library versions on which the code is tested to work fine:
Python (3.5.2)
Tensorflow (1.6.0)
Keras (2.1.6)

I am going to close the issue. Let me know if you need help with anything!
