### ISSUE TITLE
Cannot download data from google drive

### ISSUE THREAD

**Issue by shahto** [itsasimiqbal/SeBRe#5]
I tried downloading data and gets 3rd party cookies error, which is already allowed in settings.

**Comment by itsasimiqbal** [comment]
I guess you're trying to download it in incognito mode. If you're using Google Chrome browser then checking **Allow all cookies** will let you download the data. Here's a snapshot from my browser. Let me know if there's any trouble!

![image](https://user-images.githubusercontent.com/7762858/118016031-33591400-b355-11eb-8b1f-b578830fe339.png)

**Comment by shahto** [comment]
It works now. Thank you. I believe the data on google drive contains only sagittal sections while the paper mentions coronal sections as well. Is it possible to get access to labeled coronal sections as well?
